- name: Configuring hostname
  ansible.builtin.shell: set-hostname prometheus

- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus

- name: Download & extract prometheus
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /opt
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: Copying Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-3.2.1.linux-amd64/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Copying systemd file 
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Restarting service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: true